version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    depends_on:
      - postgres
    networks:
      - atlas-network

  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: atlas_test
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - atlas-network

volumes:
  postgres_data:

networks:
  atlas-network:
    driver: bridge 